# [자연어처리]
# 13주차(13-2). BERT와 [MASK]

# 202002961 김현주
* **모든 셀 실행** 후 제출하시기 바랍니다.
* **실습 (13-2-1)**이 있습니다.

> ### 중간 중간 **'### ... 이 부분을 완성하시오'** 라는 부분의 코드를 완성해 보기 바랍니다. (강의 자료를 참고하여 '???' 부분을 작성해 보시기 바랍니다.)

In [1]:
! pip install transformers

In [2]:
from transformers import TFBertForMaskedLM ### ... 이 부분을 완성하시오
from transformers import AutoTokenizer ### ... 이 부분을 완성하시오

In [3]:
model = TFBertForMaskedLM.from_pretrained('bert-large-uncased') ### ... 이 부분을 완성하시오
tokenizer = AutoTokenizer.from_pretrained('bert-large-uncased') ### ... 이 부분을 완성하시오

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.34G [00:00<?, ?B/s]

All PyTorch model weights were used when initializing TFBertForMaskedLM.

All the weights of TFBertForMaskedLM were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForMaskedLM for predictions without further training.


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [4]:
inputs = tokenizer('Soccer is a really fun [MASK].', return_tensors='tf') # MLM 예측 결과

In [5]:
print(inputs['input_ids']) # 정수 인코딩 결과

tf.Tensor([[ 101 4715 2003 1037 2428 4569  103 1012  102]], shape=(1, 9), dtype=int32)


In [6]:
print(inputs['token_type_ids']) # 세그먼트 인코딩 결과

tf.Tensor([[0 0 0 0 0 0 0 0 0]], shape=(1, 9), dtype=int32)


In [7]:
print(inputs['attention_mask']) # 어텐션 마스크 결과

tf.Tensor([[1 1 1 1 1 1 1 1 1]], shape=(1, 9), dtype=int32)


In [8]:
from transformers import FillMaskPipeline
pip = FillMaskPipeline(model=model, tokenizer=tokenizer) ### ... 이 부분을 완성하시오

In [9]:
pip('Soccer is a really fun [MASK].')

[{'score': 0.7621113061904907,
  'token': 4368,
  'token_str': 'sport',
  'sequence': 'soccer is a really fun sport.'},
 {'score': 0.20342056453227997,
  'token': 2208,
  'token_str': 'game',
  'sequence': 'soccer is a really fun game.'},
 {'score': 0.012208598665893078,
  'token': 2518,
  'token_str': 'thing',
  'sequence': 'soccer is a really fun thing.'},
 {'score': 0.001863026642240584,
  'token': 4023,
  'token_str': 'activity',
  'sequence': 'soccer is a really fun activity.'},
 {'score': 0.001335486420430243,
  'token': 2492,
  'token_str': 'field',
  'sequence': 'soccer is a really fun field.'}]

In [10]:
pip('The Avengers is a really fun [MASK].')

[{'score': 0.25628983974456787,
  'token': 2265,
  'token_str': 'show',
  'sequence': 'the avengers is a really fun show.'},
 {'score': 0.1728411316871643,
  'token': 3185,
  'token_str': 'movie',
  'sequence': 'the avengers is a really fun movie.'},
 {'score': 0.111077219247818,
  'token': 2466,
  'token_str': 'story',
  'sequence': 'the avengers is a really fun story.'},
 {'score': 0.07248973101377487,
  'token': 2186,
  'token_str': 'series',
  'sequence': 'the avengers is a really fun series.'},
 {'score': 0.07046633213758469,
  'token': 2143,
  'token_str': 'film',
  'sequence': 'the avengers is a really fun film.'}]

---

# **[[실습 13-2-1]]** 다른 예시 만들어보기
우리가 살펴본 아래의 예시처럼,
* 'Soccer is a really fun [MASK].'
* 'The Avengers is a really fun [MASK].'

[MASK]가 있는 새로운 문장을 만들어 보자!

In [ ]:
# pip('이곳에 [MASK]를 포함한 예시 문장을 작성하시오')

In [12]:
pip('Natural Language processing is [MASK].')

[{'score': 0.061441097408533096,
  'token': 2825,
  'token_str': 'possible',
  'sequence': 'natural language processing is possible.'},
 {'score': 0.04393908381462097,
  'token': 6827,
  'token_str': 'essential',
  'sequence': 'natural language processing is essential.'},
 {'score': 0.04383791983127594,
  'token': 2590,
  'token_str': 'important',
  'sequence': 'natural language processing is important.'},
 {'score': 0.03429356589913368,
  'token': 2109,
  'token_str': 'used',
  'sequence': 'natural language processing is used.'},
 {'score': 0.0334506593644619,
  'token': 11887,
  'token_str': 'optional',
  'sequence': 'natural language processing is optional.'}]

## 아래의 1~4를 작성하여 제출하시오.
1. 예시 문장은 무엇인가?
2. (코드 실행 전) 예상했던 [MASK]의 값은 무엇인가?
3. (코드 실행을 통해) Top 5로 나온 [MASK]의 값은 무엇인가?
4. 위의 2와 3에 작성한 내용을 기반으로 결과를 해석해보시오.

1. Natural Language processing is [MASK].
2. important, critical, necessary , powerful, challenging
3. possible, essential, important, uesd, optional
4. 예상했던 단어들 중에서 important만이 3순위로 나타났으며, 예상했던 단어들 보다 possible, essential, uesd, optional이 훈련 데이터에서 자주 학습했으며 보편적이고 중립적인 표현이므로 우선적으로 선택했다고 생각합니다.

---

# [파일] -> [다운로드] -> [.ipynb 다운로드]